#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("handhack_android.Resource", IsApplication=true)]

namespace handhack_android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Arc = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Circle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Fancytext = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Freehand = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Goodline = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Line = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Logo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Oval = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Rectangle = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Redo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Roundrectangle = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Roundsquare = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Square = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Text = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Undo = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int Circlelike = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int Editcanvas = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int Linelike = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int Redo = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int Squarelike = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int Startedit = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int Textlike = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int Toolbar = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Undo = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Edit = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Start = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
