#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("tegaki_hack.Resource", IsApplication=true)]

namespace tegaki_hack
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040004
			public const int FillRules = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int Linecaps = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Linejoins = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int Perses = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int rgbarray = 2130968576;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int blue = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int green = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int red = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AdjustmentIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ArcIcon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int DashedCircumference = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int FancytextIcon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int FreehandIcon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int LineIcon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Oval = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int OvalIcon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int PaintIcon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int RectangleIcon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int RedoIcon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int RegularPolygonIcon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int SaveIcon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int TextIcon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int UndoIcon = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080005
			public const int APicker = 2131230725;
			
			// aapt resource value: 0x7f080009
			public const int ASeekBar = 2131230729;
			
			// aapt resource value: 0x7f080018
			public const int Adjustment = 2131230744;
			
			// aapt resource value: 0x7f080004
			public const int BPicker = 2131230724;
			
			// aapt resource value: 0x7f080008
			public const int BSeekBar = 2131230728;
			
			// aapt resource value: 0x7f080001
			public const int ColorIndicator = 2131230721;
			
			// aapt resource value: 0x7f08001a
			public const int Editcanvas = 2131230746;
			
			// aapt resource value: 0x7f08001e
			public const int FillColor = 2131230750;
			
			// aapt resource value: 0x7f080021
			public const int FillRule = 2131230753;
			
			// aapt resource value: 0x7f080013
			public const int Freehand = 2131230739;
			
			// aapt resource value: 0x7f080003
			public const int GPicker = 2131230723;
			
			// aapt resource value: 0x7f080007
			public const int GSeekBar = 2131230727;
			
			// aapt resource value: 0x7f08000b
			public const int HSeekBar = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int HText = 2131230730;
			
			// aapt resource value: 0x7f08000f
			public const int LSeekBar = 2131230735;
			
			// aapt resource value: 0x7f08000e
			public const int LText = 2131230734;
			
			// aapt resource value: 0x7f080014
			public const int Line = 2131230740;
			
			// aapt resource value: 0x7f08001f
			public const int Linecap = 2131230751;
			
			// aapt resource value: 0x7f080020
			public const int Linejoin = 2131230752;
			
			// aapt resource value: 0x7f080022
			public const int NRegularPolygon = 2131230754;
			
			// aapt resource value: 0x7f080015
			public const int Oval = 2131230741;
			
			// aapt resource value: 0x7f080019
			public const int Paint = 2131230745;
			
			// aapt resource value: 0x7f080002
			public const int RPicker = 2131230722;
			
			// aapt resource value: 0x7f080006
			public const int RSeekBar = 2131230726;
			
			// aapt resource value: 0x7f080016
			public const int Rectangle = 2131230742;
			
			// aapt resource value: 0x7f080011
			public const int Redo = 2131230737;
			
			// aapt resource value: 0x7f080017
			public const int RegularPolygon = 2131230743;
			
			// aapt resource value: 0x7f080000
			public const int RightAngleDivision = 2131230720;
			
			// aapt resource value: 0x7f08000d
			public const int SSeekBar = 2131230733;
			
			// aapt resource value: 0x7f08000c
			public const int SText = 2131230732;
			
			// aapt resource value: 0x7f080012
			public const int Save = 2131230738;
			
			// aapt resource value: 0x7f080023
			public const int StartEdit = 2131230755;
			
			// aapt resource value: 0x7f08001b
			public const int StrokeColor = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int StrokeWidthCent = 2131230748;
			
			// aapt resource value: 0x7f08001d
			public const int StrokeWidthPers = 2131230749;
			
			// aapt resource value: 0x7f080024
			public const int SvgDialogText = 2131230756;
			
			// aapt resource value: 0x7f080010
			public const int Undo = 2131230736;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AdjustmentDialog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ColorSetter = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Edit = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PaintDialog = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int RegularPolygonDialog = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Start = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SvgDialog = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060003
			public const int AdjustmentOptions = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int Edit = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int FillColor = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int FillRule = 2131099659;
			
			// aapt resource value: 0x7f060009
			public const int Linecap = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int Linejoin = 2131099658;
			
			// aapt resource value: 0x7f060002
			public const int NVertices = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int PaintOptions = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int RegularPolygonOptions = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int RightAngleDivision = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int StrokeColor = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int StrokeWidth = 2131099655;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int CustomTheme = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int spinnerDropDownItemStyle = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int spinnerStyle = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
